// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ActionMessage: typeof import('./Jetstream/ActionMessage.vue')['default']
    ActionSection: typeof import('./Jetstream/ActionSection.vue')['default']
    AppLayout: typeof import('./Layouts/AppLayout.vue')['default']
    ApplicationLogo: typeof import('./Jetstream/ApplicationLogo.vue')['default']
    ApplicationMark: typeof import('./Jetstream/ApplicationMark.vue')['default']
    AuthenticationCard: typeof import('./Jetstream/AuthenticationCard.vue')['default']
    AuthenticationCardLogo: typeof import('./Jetstream/AuthenticationCardLogo.vue')['default']
    Banner: typeof import('./Jetstream/Banner.vue')['default']
    Breadcrumbs: typeof import('./Components/Breadcrumbs.vue')['default']
    BurgerMenu: typeof import('./Components/BurgerMenu.vue')['default']
    Button: typeof import('./Jetstream/Button.vue')['default']
    Checkbox: typeof import('./Jetstream/Checkbox.vue')['default']
    ConfirmationModal: typeof import('./Jetstream/ConfirmationModal.vue')['default']
    ConfirmsPassword: typeof import('./Jetstream/ConfirmsPassword.vue')['default']
    DangerButton: typeof import('./Jetstream/DangerButton.vue')['default']
    DialogModal: typeof import('./Jetstream/DialogModal.vue')['default']
    Dropdown: typeof import('./Jetstream/Dropdown.vue')['default']
    DropdownLink: typeof import('./Jetstream/DropdownLink.vue')['default']
    FormSection: typeof import('./Jetstream/FormSection.vue')['default']
    Input: typeof import('./Jetstream/Input.vue')['default']
    InputError: typeof import('./Jetstream/InputError.vue')['default']
    Label: typeof import('./Jetstream/Label.vue')['default']
    MainLogo: typeof import('./Components/MainLogo.vue')['default']
    Modal: typeof import('./Jetstream/Modal.vue')['default']
    Nav: typeof import('./Components/Nav.vue')['default']
    NavLink: typeof import('./Jetstream/NavLink.vue')['default']
    ProductCard: typeof import('./Components/ProductCard.vue')['default']
    ResponsiveNavLink: typeof import('./Jetstream/ResponsiveNavLink.vue')['default']
    SecondaryButton: typeof import('./Jetstream/SecondaryButton.vue')['default']
    SectionBorder: typeof import('./Jetstream/SectionBorder.vue')['default']
    SectionTitle: typeof import('./Jetstream/SectionTitle.vue')['default']
    ShopNav: typeof import('./Components/ShopNav.vue')['default']
    ShopNavLink: typeof import('./Components/ShopNavLink.vue')['default']
    TheFooter: typeof import('./Components/TheFooter.vue')['default']
    TheHeader: typeof import('./Components/TheHeader.vue')['default']
    ValidationErrors: typeof import('./Jetstream/ValidationErrors.vue')['default']
    Welcome: typeof import('./Jetstream/Welcome.vue')['default']
  }
}

export { }
